apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: csharp-weatherforecast-domain
  description: Demo Domain for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: demo-team

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: csharp-weatherforecast
  description: Demo Application's Microservice-1
  tags:
    - microservice
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=csharp-weatherforecast'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  providesApis:
   - csharp-weatherforecast-api
  lifecycle: alpha
  owner: demo-team
  system: csharp-weatherforecast


---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: csharp-weatherforecast
  description: Demo Application for Tanzu Application Platform
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: demo-team
  domain: csharp-weatherforecast-domain

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: csharp-weatherforecast-api
  description: The demo API for Tanzu Developer Portal
  links:
    - url: https://csharp-weatherforecast.default.tap.wizards.lab
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: demo-team
  system: csharp-weatherforecast # Or specify system name of your choice
  definition: |
    openapi: 3.0.1
    info:
      title: Demo API
      description: defaultDescription
      version: '0.1'
    servers:
      - url: https://csharp-weatherforecast.default.tap.wizards.lab
    paths:
      /WeatherForecast:
        get:
          description: Auto generated using Swagger Inspector
          parameters:
            - name: name
              in: query
              schema:
                type: string
              example: any_name
          responses:
            '200':
              description: Auto generated using Swagger Inspector
              content:
                application/json; charset=utf-8:
                  schema:
                    type: string
                  examples: {}